from . import rate_country
from . import rate_city
from . import project_sla
from . import rate_region
from . import project_skill
from . import project_worksite
from . import project_project_rate
from . import sale_order
from . import project_sla_line
from . import service_type
from . import rate_uplift_line
from . import res_config_settings
from . import sale_order_line
from . import sale_order_discount
from . import mail_compose_message
from . import account_move_line
from . import crm_lead_ext
from . import project_task
from . import project_project